### PR TITLE
Updates for Python 3.11 and newest version

### LINKED ISSUE #77: Update package for Python 3.11
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Package dependencies currently require `>=3.10,<3.11.0a0`.

```
Specifications:

  - reportlab -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']

Your python: python=3.11
```

### Installed packages

```shell
# packages in environment at c:\Users\user\Miniconda3\envs\temp311:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.24            h5b45459_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libsqlite                 3.39.4               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
openssl                   3.0.5                hcfcfb64_2    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
python                    3.11.0          hcf16a7b_0_cpython    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
```

### Environment info

```shell
active environment : temp311
    active env location : c:\Users\user\Miniconda3\envs\temp311
            shell level : 2
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : c:\Users\user\Miniconda3  (writable)
      conda av data dir : c:\Users\user\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : c:\Users\user\Miniconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : c:\Users\user\Miniconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### PR DESCRIPTION
**Pull request by bkpoon**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This builds off of #78 and updates `reportlab` to the latest version (3.6.12) (#80). Fixes #77 

- The installation command in `build.sh` and `bld.bat` has been updated to use `pip`
- The `pillow` dependency version has been updated
- The testing field has been updated

### CODE REVIEW

**Comment by bkpoon** [comment]
This is ready for review. Let me know if any changes are needed. Thanks!

**Comment by bkpoon** [comment]
@mcs07 When you have a chance, can you take a look at this PR? It should clear up the Python 3.11 migration and update to the latest version? Let me know if any changes are needed. Thanks!

**Comment by dopplershift** [comment]
@bkpoon If you add yourself as a maintainer following [these instructions](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username) I'd be happy to merge that PR, then you can handle this update yourself.

**Comment by bkpoon** [comment]
@dopplershift Thanks! The PR is #84

**Comment by dopplershift** [comment]
Merged!

**Pull request merged**
